# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Versão mais atualizada do código
      
      # Instalando o node, para ser possível a execução do script
      - name: Setup Node.js environment 
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
          
      # Instalar as dependências do NPM/Yarn -> para permitir a execução da build
      - name: Install dependencies
        run: yarn
        
      # Executar a build -> popula o diretório dist com os arquivos JS
      - name: Run build
        run: yarn build
        
      # Copiar a pasta dist para dentro da Digital Ocean -> Em diretório temporário
      - name: Copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"
      # Substituir o conteúdo do diretório dist da API, pelo da pasta temporária
      # Executar "yarn" na Digital Ocean -> Instalando as dependencias
      # Executar as migrations do TypeORM -> Atualizando o banco
      # Restart da API

      
